
[package]
name = "mavlink"
version = "0.5.0"
authors = ["Todd Stellanova", "Michal Podhradsky", "Kevin Mehall", "Tim Ryan"]
build = "build/main.rs"
description = "Implements the MAVLink data interchange format for UAVs."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/mavlink/rust-mavlink"

[build-dependencies]
crc16 = "0.3.3"
bytes = "0.4"
xml-rs = "0.2"
quote = "0.3"
rustfmt = "0.9"
lazy_static = "1.2.0"

[[bin]]
name = "mavlink-dump"

[dependencies]
crc16 = "0.3.3"
bytes = "0.4"
num-traits = "0.2"
num-derive = "0.2"
bitflags = "1.0.4"
serial = { version = "0.4", optional = true }

[dependencies.byteorder]
version = "0.5.3"
optional = true


[features]
"emit-description" = []
"std" = ["byteorder"]
"udp" = []
"tcp" = []
"direct-serial" = []
default= ["std", "tcp", "udp", "direct-serial", "serial"]
