[package]
name = "mavlink"
version = "0.4.1"
authors = ["Tim Ryan"]
build = "build/main.rs"
description = "Parses the MAVLink data interchange format for UAVs."
license = "MIT/Apache-2.0"
repository = "https://github.com/3drobotics/rust-mavlink"

[build-dependencies]
crc16 = "0.3.3"
byteorder = "0.5.3"
xml-rs = "0.2"

[[bin]]
name = "mavlink-dump"

[dependencies]
crc16 = "0.3.3"
byteorder = "0.5.3"
log = "0.3.6"
env_logger  = "0.3.3"
