
[package]
name = "mavlink"
version = "0.10.1"
authors = ["Todd Stellanova", "Michal Podhradsky", "Kevin Mehall", "Tim Ryan", "Patrick Jos√© Pereira", "Ibiyemi Abiodun"]
build = "build/main.rs"
description = "Implements the MAVLink data interchange format for UAVs."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/mavlink/rust-mavlink"
edition = "2018"

[build-dependencies]
crc-any = "2.3.0"
bytes = { version = "1.0", default-features = false }
quick-xml = "0.24"
quote = "1"
proc-macro2 = "1.0.43"
lazy_static = "1.2.0"
serde = { version = "1.0.115", optional = true, features = ["derive"] }

[[bin]]
name = "mavlink-dump"
required-features = ["ardupilotmega"]

[dependencies]
crc-any = "2.3.5"
bytes = { version = "1.0", default-features = false }
num-traits = { version = "0.2", default-features = false }
num-derive = "0.3.2"
bitflags = "1.2.1"
serial = { version = "0.4", optional = true }
serde = { version = "1.0.115", optional = true, features = ["derive"] }
byteorder = { version = "1.3.4", default-features = false }
embedded-hal = { version = "0.2", optional = true }
nb = { version = "1.0", optional = true }

[features]
"ardupilotmega" = ["common", "icarous", "uavionix"]
"asluav" = ["common"]
"autoquad" = ["common"]
"matrixpilot" = ["common"]
"minimal" = []
"paparazzi" = ["common"]
"python_array_test" = ["common"]
"slugs" = ["common"]
"standard" = ["common"]
"test" = []
"ualberta" = ["common"]
"uavionix" = ["common"]
"icarous" = []
"common" = ["minimal"]

"all-dialects" = [
    "ardupilotmega",
    "asluav",
    "autoquad",
    "matrixpilot",
    "minimal",
    "paparazzi",
    "python_array_test",
    "slugs",
    "standard",
    "test",
    "ualberta",
    "uavionix",
    "icarous",
    "common",
]

"emit-description" = []
"emit-extensions" = []
"std" = ["byteorder/std"]
"udp" = []
"tcp" = []
"direct-serial" = []
"embedded" = ["embedded-hal", "nb"]
default= ["std", "tcp", "udp", "direct-serial", "serial", "serde", "common"]

# build with all features on docs.rs so that users viewing documentation
# can see everything
[package.metadata.docs.rs]
features = ["default", "all-dialects", "emit-description", "emit-extensions"]
